language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
services:
  - redis-server
install:
  - composer install --prefer-source --no-interaction
before_script:
  - chmod u+x php-rq-run-tests
script:
  - REDIS_HOST=localhost REDIS_DB=0 ./php-rq-run-tests
